services:
  postgres:
    image: postgres:16
    container_name: delivery-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: delivery-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/mydb
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data: